baseURL = 'https://snakecaptain.github.io/mylogs/'
languageCode = 'zh-hk'
title = '原木印記'
theme = 'beautifulhugo'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[menu]

  [[menu.main]]
    identifier = "home"
    name = "首頁"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "文章"
    url = "/post/"
    weight = 3
